# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DLR WebView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DLR WebView
  pod "GCDWebServer", "~> 3.0"

end
